# Generated by Django 6.0.2 on 2026-02-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_customerprofile_emailotp_cartitem_wishlistitem'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailotp',
            name='products_em_email_5642c4_idx',
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
