# Generated by Django 6.0.2 on 2026-02-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('General', 'General'), ('Order', 'Order related'), ('Payment', 'Payment'), ('Delivery', 'Delivery'), ('Other', 'Other')], default='General', max_length=30)),
                ('order_id', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
