# Generated by Django 6.0.2 on 2026-02-08 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_enquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enquiries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
